/**
 * Permission identifiers are grouped by resource for discoverability while
 * retaining a flat string value suitable for storage and RBAC checks.
 */
export const PERMISSIONS = {
  AUTH_LOGIN: "AUTH_LOGIN",
  ONBOARDING_COMPLETE_SELF: "ONBOARDING_COMPLETE_SELF",

  PROFILE_VIEW_SELF: "PROFILE_VIEW_SELF",
  PROFILE_VIEW_PUBLIC: "PROFILE_VIEW_PUBLIC",
  PROFILE_UPDATE_SELF: "PROFILE_UPDATE_SELF",
  PRIVACY_UPDATE_SELF: "PRIVACY_UPDATE_SELF",

  ACADEMIC_VIEW_SELF: "ACADEMIC_VIEW_SELF",
  ACADEMIC_VIEW_PUBLIC_IF_ALLOWED: "ACADEMIC_VIEW_PUBLIC_IF_ALLOWED",
  ACADEMIC_VIEW_ALL: "ACADEMIC_VIEW_ALL",

  USER_SEARCH: "USER_SEARCH",
  USER_SUSPEND: "USER_SUSPEND",

  ROLE_ASSIGN_GLOBAL: "ROLE_ASSIGN_GLOBAL",
  ROLE_ASSIGN_CLASS_CR: "ROLE_ASSIGN_CLASS_CR",
  ROLE_ASSIGN_SOCIETY: "ROLE_ASSIGN_SOCIETY",

  CLASS_VIEW_OWN: "CLASS_VIEW_OWN",
  CLASS_VIEW_MEMBERS_OWN: "CLASS_VIEW_MEMBERS_OWN",
  CLASS_CREATE: "CLASS_CREATE",
  CLASS_UPDATE: "CLASS_UPDATE",
  CLASS_ASSIGN_STUDENT: "CLASS_ASSIGN_STUDENT",
  CLASS_ANNOUNCEMENT_VIEW: "CLASS_ANNOUNCEMENT_VIEW",
  CLASS_ANNOUNCEMENT_CREATE: "CLASS_ANNOUNCEMENT_CREATE",
  CLASS_ANNOUNCEMENT_UPDATE: "CLASS_ANNOUNCEMENT_UPDATE",
  CLASS_ANNOUNCEMENT_DELETE: "CLASS_ANNOUNCEMENT_DELETE",
  CLASS_TASK_CREATE: "CLASS_TASK_CREATE",
  CLASS_TASK_UPDATE: "CLASS_TASK_UPDATE",
  CLASS_TASK_DELETE: "CLASS_TASK_DELETE",
  CLASS_TASK_COMPLETE_SELF: "CLASS_TASK_COMPLETE_SELF",
  CLASS_TASK_VIEW_COMPLETION_SUMMARY: "CLASS_TASK_VIEW_COMPLETION_SUMMARY",

  NOTICE_VIEW: "NOTICE_VIEW",
  NOTICE_CREATE_OFFICIAL: "NOTICE_CREATE_OFFICIAL",
  NOTICE_CREATE_SOCIETY: "NOTICE_CREATE_SOCIETY",
  NOTICE_UPDATE_OWN: "NOTICE_UPDATE_OWN",
  NOTICE_DELETE: "NOTICE_DELETE",

  SOCIETY_VIEW_PUBLIC: "SOCIETY_VIEW_PUBLIC",
  SOCIETY_CREATE: "SOCIETY_CREATE",
  SOCIETY_UPDATE_PROFILE: "SOCIETY_UPDATE_PROFILE",
  SOCIETY_ARCHIVE: "SOCIETY_ARCHIVE",
  SOCIETY_INVITE_MEMBER: "SOCIETY_INVITE_MEMBER",
  SOCIETY_ACCEPT_INVITE_SELF: "SOCIETY_ACCEPT_INVITE_SELF",
  SOCIETY_REQUEST_MEMBERSHIP_SELF: "SOCIETY_REQUEST_MEMBERSHIP_SELF",
  SOCIETY_REVIEW_JOIN_REQUEST: "SOCIETY_REVIEW_JOIN_REQUEST",
  SOCIETY_REMOVE_MEMBER: "SOCIETY_REMOVE_MEMBER",
  SOCIETY_VIEW_PRIVATE_SPACE: "SOCIETY_VIEW_PRIVATE_SPACE",
  SOCIETY_ASSIGN_POR: "SOCIETY_ASSIGN_POR",

  EVENT_VIEW: "EVENT_VIEW",
  EVENT_CREATE: "EVENT_CREATE",
  EVENT_UPDATE_OWN_SOCIETY: "EVENT_UPDATE_OWN_SOCIETY",
  EVENT_CANCEL: "EVENT_CANCEL",
  EVENT_MARK_INTERESTED: "EVENT_MARK_INTERESTED",
  EVENT_REGISTER_SELF: "EVENT_REGISTER_SELF",
  EVENT_CANCEL_REGISTRATION_SELF: "EVENT_CANCEL_REGISTRATION_SELF",
  EVENT_JOIN_WAITLIST: "EVENT_JOIN_WAITLIST",
  EVENT_VIEW_REGISTRATIONS: "EVENT_VIEW_REGISTRATIONS",
  EVENT_EXPORT_REGISTRATIONS: "EVENT_EXPORT_REGISTRATIONS",

  GAZETTE_UPLOAD: "GAZETTE_UPLOAD",
  GAZETTE_PARSE_TRIGGER: "GAZETTE_PARSE_TRIGGER",
  GAZETTE_VIEW_ERRORS: "GAZETTE_VIEW_ERRORS",
  GAZETTE_FIX_RECORDS: "GAZETTE_FIX_RECORDS",

  FILE_UPLOAD_PROFILE_IMAGE: "FILE_UPLOAD_PROFILE_IMAGE",
  FILE_UPLOAD_NOTICE_ATTACHMENT: "FILE_UPLOAD_NOTICE_ATTACHMENT",
  FILE_UPLOAD_EVENT_POSTER: "FILE_UPLOAD_EVENT_POSTER",
  FILE_UPLOAD_GAZETTE: "FILE_UPLOAD_GAZETTE",

  ADMIN_DASHBOARD_VIEW: "ADMIN_DASHBOARD_VIEW",
  AUDIT_LOG_VIEW: "AUDIT_LOG_VIEW",
  CONTENT_MODERATE: "CONTENT_MODERATE",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_CODES = Object.freeze(
  Object.values(PERMISSIONS)
) as readonly PermissionCode[];

export function isPermissionCode(value: unknown): value is PermissionCode {
  return (
    typeof value === "string" &&
    PERMISSION_CODES.includes(value as PermissionCode)
  );
}
