export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  STUDENT: "STUDENT",
  CLASS_CR: "CLASS_CR",
  SOCIETY_PRESIDENT: "SOCIETY_PRESIDENT",
  SOCIETY_VICE_PRESIDENT: "SOCIETY_VICE_PRESIDENT",
  SOCIETY_MEMBER: "SOCIETY_MEMBER",
} as const;
