export const AUDIT_ACTIONS = {
  GLOBAL_ROLE_ASSIGNED: "GLOBAL_ROLE_ASSIGNED",
  GLOBAL_ROLE_REVOKED: "GLOBAL_ROLE_REVOKED",
  CLASS_ROLE_ASSIGNED: "CLASS_ROLE_ASSIGNED",
  CLASS_ROLE_REVOKED: "CLASS_ROLE_REVOKED",
  SOCIETY_ROLE_ASSIGNED: "SOCIETY_ROLE_ASSIGNED",
  SOCIETY_ROLE_REVOKED: "SOCIETY_ROLE_REVOKED",
  USER_SUSPENDED: "USER_SUSPENDED",
  USER_REACTIVATED: "USER_REACTIVATED",
  CLASS_ANNOUNCEMENT_CREATED: "CLASS_ANNOUNCEMENT_CREATED",
  CLASS_ANNOUNCEMENT_UPDATED: "CLASS_ANNOUNCEMENT_UPDATED",
  CLASS_ANNOUNCEMENT_DELETED: "CLASS_ANNOUNCEMENT_DELETED",
  CLASS_TASK_CREATED: "CLASS_TASK_CREATED",
  CLASS_TASK_UPDATED: "CLASS_TASK_UPDATED",
  CLASS_TASK_DELETED: "CLASS_TASK_DELETED",
} as const;

export const AUDIT_TARGET_TYPES = {
  USER: "USER",
  ROLE: "ROLE",
  CLASS_ROLE: "CLASS_ROLE",
  SOCIETY_ROLE: "SOCIETY_ROLE",
  CLASS: "CLASS",
  SOCIETY: "SOCIETY",
  CLASS_ANNOUNCEMENT: "CLASS_ANNOUNCEMENT",
  CLASS_TASK: "CLASS_TASK",
} as const;
