export const AUTH_PROVIDER = "google" as const;
export const OFFICIAL_EMAIL_DOMAIN = "nsut.ac.in" as const;

export const AUTH_COOKIE_NAMES = {
  SESSION: "mynsut_session",
  OAUTH_STATE: "mynsut_oauth_state",
  OAUTH_NONCE: "mynsut_oauth_nonce",
  OAUTH_CODE_VERIFIER: "mynsut_oauth_code_verifier",
} as const;

export const AUTH_ERROR_CODES = {
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  INVALID_SESSION: "INVALID_SESSION",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
  ONBOARDING_REQUIRED: "ONBOARDING_REQUIRED",
  ONBOARDING_ALREADY_COMPLETED: "ONBOARDING_ALREADY_COMPLETED",
  INSUFFICIENT_ROLE: "INSUFFICIENT_ROLE",
  INSUFFICIENT_PERMISSION: "INSUFFICIENT_PERMISSION",
  INVALID_OAUTH_STATE: "INVALID_OAUTH_STATE",
  INVALID_OAUTH_RESPONSE: "INVALID_OAUTH_RESPONSE",
  GOOGLE_AUTHENTICATION_FAILED: "GOOGLE_AUTHENTICATION_FAILED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  INVALID_EMAIL_DOMAIN: "INVALID_EMAIL_DOMAIN",
  GOOGLE_SUBJECT_CONFLICT: "GOOGLE_SUBJECT_CONFLICT",
  OAUTH_CONFIGURATION_ERROR: "OAUTH_CONFIGURATION_ERROR",
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
